name: "create simple image"

on:
  push:
    branches:
      - master

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: list directory before checkout
        run: |
          ls

      - name: checkout repository
        uses: actions/checkout@v5

      # - name: build image
      #   run: |
      #     docker build -t 17csc028/codeplay .

      # - name : login  to docker hub
      #   run: |
      #     docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{secrets.DOCKER_PASSWORD}}

      # - name :push image to dockerhub
      #   run: |
      #     docker push 17csc028/codeplay
